services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env  # Load environment variables from .env
    ports:
      - "8001:80"
    volumes:
      - .:/app